QA.BASEURI=http://34.66.197.232/api
DEV.BASEURI=http://34.66.197.232/api
UAT.BASEURI=http://34.66.197.232/api

QA.USEREMAIL=user@technocredits.com
QA.USERPWD=User@123

QA.OWNEREMAIL=owner.cafe@technocredits.com
QA.OWNERPWD=Owner@123

QA.ADMINEMAIL=admin@technocredits.com
QA.ADMINPWD=Admin@123



